# ------------------------------------------------------------------
# Stakeholder IAM users (read-only AWS console + EKS view access).
# Console passwords + programmatic keys are generated by Terraform
# and emitted as sensitive outputs. State holds them in plaintext;
# acceptable for a 2-week demo with a local backend on your laptop.
# ------------------------------------------------------------------

resource "aws_iam_user" "cto" {
  name          = "acme-cto-readonly"
  force_destroy = true
}

resource "aws_iam_user" "vp" {
  name          = "acme-vp-readonly"
  force_destroy = true
}

resource "aws_iam_user_policy_attachment" "cto_readonly" {
  user       = aws_iam_user.cto.name
  policy_arn = "arn:aws:iam::aws:policy/ReadOnlyAccess"
}

resource "aws_iam_user_policy_attachment" "vp_readonly" {
  user       = aws_iam_user.vp.name
  policy_arn = "arn:aws:iam::aws:policy/ReadOnlyAccess"
}

resource "aws_iam_user_login_profile" "cto" {
  user                    = aws_iam_user.cto.name
  password_length         = 24
  password_reset_required = false

  lifecycle {
    ignore_changes = [password_length, password_reset_required]
  }
}

resource "aws_iam_user_login_profile" "vp" {
  user                    = aws_iam_user.vp.name
  password_length         = 24
  password_reset_required = false

  lifecycle {
    ignore_changes = [password_length, password_reset_required]
  }
}

resource "aws_iam_access_key" "cto" {
  user = aws_iam_user.cto.name
}

resource "aws_iam_access_key" "vp" {
  user = aws_iam_user.vp.name
}
